DROP TABLE IF EXISTS gym_member CASCADE;

CREATE TABLE gym_member (
	id INT AUTO_INCREMENT,
	account_number VARCHAR(5) UNIQUE NOT NULL, 
	first_name VARCHAR(50) NOT NULL, 
	last_name VARCHAR(50) NOT NULL, 
	age INT NOT NULL,
	email VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
	);